language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "gift-manager-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: gift-manager
  api_key:
    secure: "ociGMbLTpIFJrUa2ddt9I8sDau9fql55LFXWlzTyfVAHwxd2+l9tjo7foGjCjgDI5BEU7wGfEvXgtA1wIfXXX/+bH4mVDmusE+g1v83ViidnPL1
Tj8cXglR9G2e5K7v+tCZqz+BygN92yjYl0erMIBPUM6Yha4kqpJp3hGtb5kbwOLmpppkxoknbC00iDEmNKv0KyBCCYdkRNiPZHQRB7DGwUTU/3ecjo29UGhio3
2IDlPP0TXYnSjPOwOfn/EqiHWu3jwu6Bik2pZy6RcpxzO3s0QN5xfMUh6p0TjrXvzJsSy52zuURbXmeJiyJ6e1UNV/Gi273Umye7fxAeH93i7R18QgwQUKF/pb
oBqsVVEdjfW3umUiA9LKXiH/f5Lf+AGACeYxLf5oqT86CWa6Kb/mn9yTom3s3A1ipXQHkF0PXD9q/RioLQaHjHQximCIw5waulWf9CSW8Fv+zG153nzmX3LrLr
LO4TmST2KhklEse3opQcV6oQZ/wmVcI1pey/cm3+PO4CMwp9yEJr9MGqgI/ktDOyNSZtvVNb4W5mHiocPOTys0e75EbGGg4QMvWTDd1c5PrjkrBgNGnE0Hy/nwLPsqqzC/vjDDuSpEFE09Pi6ETNZTQkG7sFygPGu/i0gJ4ty/k1tA1ENmOb48F+Df2DixIKLxjZwfG3PdF54g="
